core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tarefas/admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('todo/', include('todo.urls'), name='todo'),
    path('login/', include('authentication.urls'), name='login'),
    path('recover/', include('recover.urls'), name='recover'),
]

handler404 = "home.views.handler404"

home/urls.py
from django.urls import path

from .views import contact, index, new_user, sended

app_name='home'

urlpatterns = [
    path('', index, name='index'),
    path('registro/', new_user, name='registro'),
    path('registro/contato/', contact, name='contato'),
    path('registro/contato/sended/', sended, name='enviado'),
]

todo/urls.py
from django.urls import path

from .views import create_task, delete_task, list, update_task

app_name='todo'

urlpatterns = [
    path('', list, name='list'),
    path('create/', create_task, name='create'),
    path('update/<int:id>/', update_task, name='update'),
    path('delete/<int:id>/', delete_task, name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms/form_contact.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=80,
        required=True,
        widget= forms.TextInput(
            attrs={
                'class':'input-field',
                'placeholder':'Nome',
                'type':'text',
            }
        ),
    )
    email = forms.EmailField(
        required=True,
        widget= forms.EmailInput(
            attrs={
                'class':'input-field',
                'placeholder':'E-mail',
                'type':'email',
            }
        ),
    )
    message = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                'class':'input-field',
                'placeholder':'Sua mensagem',
                'type':'text',
            }
        )
    )
    
    def get_info(self):
        clean_data = super().clean()
        
        name = clean_data.get('name').strip()
        from_mail = clean_data.get('email')
        message = f"{name} entrou em contato com o e-mail: {from_mail} e disse:"
        message+= f"\n{clean_data.get('message')}"
        
        return message

home/forms/form_register.py
from django.contrib.auth.models import User
from django.forms import ModelForm


class RegisterUserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','password','email',)

home/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse

from home.forms.form_contact import ContactForm
from home.forms.form_register import RegisterUserForm


def index(request):
    form_contact = ContactForm()
    return render(request, 'home/index.html',{
        'form_contact':form_contact,
        'contact':reverse('home:contato')
        }
    )

def new_user(request):
    if request.POST:
        form_new_user= RegisterUserForm(request.POST)
    else:    
        form_new_user= RegisterUserForm()
    return render(request, 'home/form_user.html',{'userForm':form_new_user})

def handler404(request, exception):
    return render(request, 'home/page_error.html')


def contact(request):
    if not request.POST:
        return redirect('home:index')
 
    form = ContactForm(request.POST)
  
    if form.is_valid():
        subject= "Contato via App Tarefas."
        message= f"Mensagem enviada por {form.cleaned_data.get('name')},"
        message+= f"\nE-mail: {form.cleaned_data.get('email')}"
        message+= f"\n\n{form.cleaned_data.get('message')}"
        message+= "\n\n Via App Tarefas!"
        recipient= [settings.EMAIL_HOST_USER,]
        send_mail(
            subject=subject, 
            message=message,
            from_email=form.cleaned_data.get('email'),
            recipient_list=recipient, 
            fail_silently=False,
        )
        messages.success(request, 'Sua mensagem foi enviada com sucesso!')
        return redirect('home:enviado')

def sended(request):
    return render(request, 'home/email_success.html')

home/templates/home/email_success.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="6;url={% url 'home:index' %}">
    <title>E-mail enviado</title>
    <style>
        html {
            background: linear-gradient(to bottom, rgba(39, 63, 110, 0.8) 100%, rgba(27, 152, 224, 0.8) 0%),
            url("{% static 'assets/img/sended_mail.png' %}");
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: scroll;
            background-size: cover;
            height: 100%;
        }

        h1 {
            text-align: center;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
            font-size: 2.5rem;
            color: rgba(255, 255, 255, 0.445);
            text-shadow: -1px -1px rgba(39, 63, 110, 1);
            text-transform: uppercase;
        }

        h3 {
            margin-top: 22px;
            text-align: center;
            font-family: Arial;
            color: rgba(0, 204, 255, 0.856);
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }

        a {
            width: 20%;
            margin-top: 5%;
            text-align: center;
            box-shadow: 1px 1px rgba(55, 55, 55, 0.5);
            background-color: rgba(27, 152, 224, 0.4);
            border-radius: 28px;
            display: inline-block;
            cursor: pointer;
            color: #ffffff;
            font-family: Arial;
            font-size: 18px;
            padding: 16px 76px;
            text-decoration: none;
            transition: ease-in-out 0.50s;
        }

        a:hover {
            background-color: rgba(29, 5, 165, 0.3);
        }

        a:active {
            position: relative;
            top: 1px;
        }

        .container {
            padding: 10%;
            display: flex;
            flex-wrap: wrap;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>E-mail enviado com sucesso!</h1>
        <h3>Obrigado por enviar uma mensagem!,<br>
            <p>em breve retornarei o contato!</p>
        </h3>
        <a href="{% url 'home:index' %}">Página inicial</a>
    </div>
</body>

</html>

home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}Tarefas - Não deixe de fazê-las{% endblock %}

{% block navbar %}{% include 'parts/navbar.html' %}{% endblock %}
{% block header %}{% include 'parts/header.html' %}{% endblock %}

{% block main %}
<!-- sobre o projeto -->
<section class="page-section bg-primary bg-about" id="about">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
            <h2 class="text-white mt-0">Simplesmente fácil!</h2>
            <hr class="divider divider-light" />
            <p class="text-white-75 mb-4">Ao digitar uma tarefa, ela estará associada a data em que foi lançada.
                E quando você cumprir sua tarefa, basta marcar como concluída e você verá o status diferente das 
                demais tarefas que ainda precisam ser cumpridas.</p>
                <p class="text-white-75 mb-4">E se precisar reabrir a mesma tarefa, você pode simplesmente desmarcar ela como
                concluída, e ela estará disponível novamente com data atualizada. Assim você poderá sempre ter acesso as
                suas tarefas atuais e poderá cumprir as tarefas em outro momento sem esquecer de nenhuma delas.</p>
                <a class="btn btn-light btn-xl" href="{% url 'todo:list' %}">Começe agora!</a>
            </div>
        </div>
    </div>
</section>
<!-- Portfolio-->
<section class="page-section text-white bg-portifolio"  id="portfolio">
    <div class="social-midia">
        <div class="p-5 text-center">
            <h2 class="mb-3">Meu GitHub</h2>
            <a class="display-1" href="https://github.com/fspjonny" target="_blank"><i class="fa-brands fa-github"></i></a>
        </div>
        <div class="p-5 text-center">
            <h2 class="mb-3">Meu Linkedin</h2>
            <a class="display-1" href="https://www.linkedin.com/in/fabiosilvapedro19071976/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
        </div>
    </div>
</section>
<!-- Contato -->
<section class="page-section form-contact" id="contact">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0 title-text">Entre em contato!</h2>
                <hr class="divider" />
                <p class="text-muted mb-5">Se gostou do meu trabalho e achou útil este pequeno projeto, fique a vontade para 
                    continuar a usá-lo ou então quer saber como eu o fiz, você poderá baixar o código no meu 
                    <a href="https://github.com/fspjonny" target="_blank">Github</a></p>
                    <span class="title-text">Envie seus elogios ou dúvidas, que respondo em breve.</span>
            </div>
        </div>
        <div class="justify-content-center">
            {% if messages %}
                {% for message in messages %}
                <p class="text-primary text-center">{{message}}</p>
                {% endfor %}
            {% endif %}
            <form class="global-form" action="{{contact}}" method="POST" enctype="application/x-www-form-urlencoded">
                {% csrf_token %}
                {% for field in form_contact %}
                    {{field}}
                {% endfor %}
                <button class="button-form full" type="submit"><i class="fa-solid fa-envelope-circle-check"></i> Enviar</button>
            </form>            
        </div>
    </div>
</section>
{% endblock %}

home/templates/home/page_error.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">    
    <meta http-equiv="refresh" content="10;url={% url 'home:index' %}">
    <title>Página não encontrada</title>
    <style>
        html {
            background: linear-gradient(to bottom, rgba(255, 94, 0, 0.5) 100%, rgba(219, 77, 7, 0.5) 0%),
            url("{% static 'assets/img/404_page.png' %}");
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: scroll;
            background-size: cover;
            height: 100%;
        }

        h1 {
            text-align: center;
            font-family: 'Montserrat', sans-serif;
            font-size: 2.4rem;
            color: rgba(255, 255, 255, 0.8);
            text-shadow: -1px 1px rgba(0, 0, 0, 0.8), -1px -1px rgba(255, 255, 255, 0.9);
            text-transform: uppercase;
        }

        h3 {
            margin-top: 22px;
            text-align: center;
            font-family: 'Montserrat', sans-serif;
            color: #fff;
            text-transform: uppercase;
        }

        a {
            margin-top: 5%;
            text-align: center;
            box-shadow: 1px 1px rgba(55, 55, 55, 0.5);
            background-color: rgba(255, 255, 255, 0.4);
            border-radius: 28px;
            display: inline-block;
            cursor: pointer;
            color: #ffffff;
            font-family: 'Montserrat', sans-serif;
            font-size: 18px;
            padding: 16px 76px;
            text-decoration: none;
            transition: ease-in-out 0.50s;
        }

        @media (max-width:300px) {
            a {
                padding: 8px 76px;
                font-size: 18px;
                display: inline;
                border-radius: 40px;
            }
            
        }

        a:hover {
            background-color: rgba(255, 255, 155, 0.3);
        }

        a:active {
            position: relative;
            top: 1px;
        }

        .container {
            padding: 10%;
            display: flex;
            flex-wrap: wrap;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    <div class="container">
        <h3>Erro 404</h3>
        <h1>Perdeu o seu caminho?</h1>
        <h3>Desculpe, Eu não consegui encontrar esta página!<br>
            <p>Mas você poderá encontrar outras na página inicial.</p>
        </h3>
        <a href="{% url 'home:index' %}">Página inicial</a>
    </div>
</body>

</html>