authentication/urls.py
from django.urls import path

from authentication.views.login_view import (login_verification, logon_view,
                                             logout_view)
from authentication.views.user_create_view import createLogin, createUser
from authentication.views.user_update_view import user_settings

app_name='authentication'

urlpatterns = [
    path('', logon_view, name='logon'),
    path('register/', createUser, name='register'),
    path('create/', createLogin, name='createlogin'),
    path('autorization/', login_verification, name='login_verification'),
    path('logout/', logout_view, name='logout'),
    path('settings/', user_settings, name='settings'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tarefas/admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('todo/', include('todo.urls'), name='todo'),
    path('login/', include('authentication.urls'), name='login'),
    path('recover/', include('recover.urls'), name='recover'),
]

handler404 = "home.views.handler404"

home/urls.py
from django.urls import path

from .views import contact, index, new_user, sended

app_name='home'

urlpatterns = [
    path('', index, name='index'),
    path('registro/', new_user, name='registro'),
    path('registro/contato/', contact, name='contato'),
    path('registro/contato/sended/', sended, name='enviado'),
]

recover/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from recover.views import MyPasswordResetConfirmView, MyPasswordResetView

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('reset-password/', MyPasswordResetView.as_view(
        template_name='recover/password_reset.html'), 
         name='reset_password'
    ),
    path('reset-password-sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='recover/password_reset_done.html'), 
         name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', 
         MyPasswordResetConfirmView.as_view(
             template_name='recover/password_reset_confirm.html'), 
         name='password_reset_confirm'
    ),
    path('reset-password-complete/', 
         auth_views.PasswordResetCompleteView.as_view(
             template_name='recover/password_reset_confirm_done.html'), 
         name='password_reset_complete'
    ),    
]

recover/models.py
from django.db import models

# Create your models here.

recover/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       PasswordResetForm, SetPasswordForm)


class MyPasswordResetForm(PasswordResetForm):
    
    email = forms.EmailField(
    label="",
    max_length=254,
    widget=forms.EmailInput(
        attrs={
            "class":"input-field",
            "autocomplete": "email",
            "placeholder": "Seu email de cadastro",
            }
        ),
    )

        
class MySetPasswordForm(SetPasswordForm):

    error_messages = {
        "password_mismatch": "Os dois campos de senha não correspondem.",
    }
    new_password1 = forms.CharField(
        label="",
        widget=forms.PasswordInput(
            attrs={
                "class":"input-field",
                "autocomplete": "new-password",
                "placeholder": "nova senha",
                }
            ),
        strip=False,
        help_text="",
    )
    new_password2 = forms.CharField(
        label="",
        strip=False,
        widget=forms.PasswordInput(attrs={
            "class":"input-field",
            "autocomplete": "new-password",
            "placeholder": "repita a nova senha",
            }
        ),
    )
    

recover/views.py
from django.contrib.auth.views import (PasswordResetConfirmView,
                                       PasswordResetView)

from recover.forms import MyPasswordResetForm, MySetPasswordForm


class MyPasswordResetView(PasswordResetView):
    form_class = MyPasswordResetForm
    email_template_name = "recover/password_reset_email.html"
    


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = MySetPasswordForm

recover/templates/recover/password_reset.html
{% extends 'base.html' %}

{% block title %}Tarefas | Recuperação de senha{% endblock %}

{% block main %}
<div class="recover-account-container">
    <div class="recover-account-reset"></div>

    <div class="recover-account-form-reset">
        <h3 class="title-text pt-2 text-center">Recuperar minha senha</h3>
        <p class="presentation-text pl-3 pr-3">Esqueceu a sua senha?</p>
        <p class="presentation-text pl-3 pr-3">Forneça o seu endereço de email de cadastro, e eu te envio um email com instruções para configurar uma senha nova.</p>

        <form class="global-form" method="post">
            {% csrf_token %}
            {{form}}
            <button class="button-form-solid full" type="submit"><i class="fa-solid fa-envelope"></i> Enviar e-mail</button>
        </form>
    </div>

</div>

<div class="grid-navigation">
    <a class="navigation-button" href="{% url 'home:index' %}"><i class="fa-solid fa-circle-arrow-left"></i></a> 
</div>
{% endblock %}

recover/templates/recover/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Tarefas | Nova senha de acesso{% endblock %}

{% block main %}
<div class="recover-account-container">

    <div class="recover-account-reset-pass"></div>

    <div class="recover-account-form-pass">
        <h3 class="title-text pt-2 text-center">Digite a nova senha</h3>
        
        <p class="help-text text-center">Por favor, informe sua nova senha duas vezes para que se possa verificar se você a digitou corretamente.</p>
    
        <h4 class="presentation-title text-center mt-4">Atenção!</h4>
        
        <ul class="list-text-left pl-1 pr-1">
            <li class="presentation-text">Sua senha não pode ser muito parecida com o resto das suas informações pessoais.</li>
            <li class="presentation-text">Sua senha precisa conter pelo menos 8 caracteres.</li>
            <li class="presentation-text">Sua senha não pode ser uma senha comumente utilizada.</li>
            <li class="presentation-text">Sua senha não pode ser inteiramente numérica.</li>
            <li class="presentation-text">Utilize Letras, números e @/./+/-/_ apenas.</li>
        </ul>
    
        <form class="global-form" method="post">
            {% csrf_token %}
            {{form}}
            <button class="button-form-solid full" type="submit"><i class="fa-solid fa-arrows-rotate"></i> Alterar minha senha</button>
        </form>
    </div>

</div>
{% endblock %}

recover/templates/recover/password_reset_confirm_done.html
{% extends 'base.html' %}

{% block title %}Tarefas | Recuperação efetivada{% endblock %}

{% block main %}
<div class="recover-account-container">
    <div class="recover-account-reset-pass-done"></div>
    
    <div class="recover-account-form-pass-done">
        <h3 class="title-text pt-2 text-center">Redefinição de senha completa</h3>
        <hr class="divisor">
        
        <p class="presentation-text pl-3 pr-3">Sua senha foi redefinida.</p>
        <p class="presentation-text pl-3 pr-3">Você pode prosseguir e se autenticar agora.</p>
        
        <div class="global-form">
            <a class="button-form-solid full" href="{% url 'authentication:logon' %}"><i class="fa-solid fa-key"></i> Proceder para Login</a>
        </div>
    </div>
</div>
{% endblock %}

recover/templates/recover/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Tarefas | Aviso de redefinição de senha{% endblock %}

{% block main %}
<div class="recover-account-container">
    <div class="recover-account-reset-done"></div>
    
    <div class="recover-account-form-reset-done">
        <h3 class="title-text pt-3 text-center">Uma redefinição de senha foi enviada!</h3>
        
        <p class="presentation-text pl-3 pr-3">Enviei um email com um link e instruções para você configurar sua senha.</p>
        
        <p class="presentation-text pl-3 pr-3">Tenha certeza que o email informado é o da sua conta, e você receberá a mensagem em breve.</p>
        
        <p class="presentation-text pl-3 pr-3">Se caso você não recebeu um email, por favor certifique-se de que você forneceu o endereço que você está cadastrado, e 
            verifique também a sua pasta de <span>spam</span>.</p>
    </div>
</div>
<div class="grid-navigation">
    <a class="navigation-button" href="{% url 'authentication:logon' %}"><i class="fa-solid fa-circle-arrow-left"></i></a> 
</div>    
{% endblock %}

recover/templates/recover/password_reset_email.html
{% load i18n %}{% autoescape off %}
{{ user.first_name }}{% blocktranslate %}, você está recebendo este e-mail porque solicitou uma redefinição de senha para sua conta de usuário em {{ site_name }}.{% endblocktranslate %}

{% translate "Por favor, vá para esta página do link abaixo e lá escolha uma nova senha:" %}
{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'Este é o seu email de usuário:' %} {{ user.email }} {% translate ', utilize-o com sua nova senha para fazer o login.' %}

{% translate "Obrigado por usar meu App!" %}

{% blocktranslate %}Suporte do: {{ site_name }}{% endblocktranslate %}

{% endautoescape %}