authentication/urls.py
from django.urls import path

from authentication.views.login_view import (login_verification, logon_view,
                                             logout_view)
from authentication.views.user_create_view import createLogin, createUser
from authentication.views.user_update_view import user_settings

app_name='authentication'

urlpatterns = [
    path('', logon_view, name='logon'),
    path('register/', createUser, name='register'),
    path('create/', createLogin, name='createlogin'),
    path('autorization/', login_verification, name='login_verification'),
    path('logout/', logout_view, name='logout'),
    path('settings/', user_settings, name='settings'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tarefas/admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('todo/', include('todo.urls'), name='todo'),
    path('login/', include('authentication.urls'), name='login'),
    path('recover/', include('recover.urls'), name='recover'),
]

handler404 = "home.views.handler404"

home/urls.py
from django.urls import path

from .views import contact, index, new_user, sended

app_name='home'

urlpatterns = [
    path('', index, name='index'),
    path('registro/', new_user, name='registro'),
    path('registro/contato/', contact, name='contato'),
    path('registro/contato/sended/', sended, name='enviado'),
]

todo/urls.py
from django.urls import path

from .views import create_task, delete_task, list, update_task

app_name='todo'

urlpatterns = [
    path('', list, name='list'),
    path('create/', create_task, name='create'),
    path('update/<int:id>/', update_task, name='update'),
    path('delete/<int:id>/', delete_task, name='delete'),
]

todo/models.py
from django.contrib.auth.models import User
from django.db import models


class ToDoModel(models.Model):
    class Meta:
        verbose_name= 'Tarefa'
        verbose_name_plural= 'Tarefas'
        
    autor = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        null=True, 
        verbose_name='Autor'
    )    
    data_de_criacao = models.DateTimeField(
        auto_now=True,
        verbose_name='Data da Tarefa'
    )
    tarefa = models.CharField(
        max_length=120,
        unique=False, 
        null=False, 
        blank=False, 
        verbose_name='Tarefa'
    )
    concluida = models.BooleanField(verbose_name='Concluído')
    
    def __str__(self) -> str:
        return self.tarefa

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError

from todo.models import ToDoModel


class ToDoForm(forms.ModelForm):
    class Meta:
        model= ToDoModel
        
        fields = [
            'tarefa',
        ]



    def clean_tarefa(self):
        text_task= self.cleaned_data.get('tarefa')
        if len(text_task) < 8:
            raise ValidationError(
            ('Tarefa não pode ter menos que 8 caracteres'),
            code='invalid',
        )
        return text_task

todo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ToDoForm
from .models import ToDoModel


@login_required(login_url='authentication:logon', redirect_field_name='next')
def list(request):
    lista_tarefas = ToDoModel.objects.filter(
        autor=request.user.id
        ).order_by('concluida','-data_de_criacao')

    data_in_session = request.session.get('register_form_data', None)    
    form = ToDoForm(data_in_session)
    return render(request, 'todo/todo_list.html',{
        'form':form,
        'form_action':reverse('todo:list'),
        'lista':lista_tarefas,
    })


@login_required(login_url='authentication:logon', redirect_field_name='next')
def create_task(request):
    if not request.POST:
        raise Http404()
    
    sended_post = request.POST
    request.session['register_form_data'] = sended_post
    form = ToDoForm(sended_post)
    
    if form.is_valid():
        data = form.save(commit=False)
        no_space= data.tarefa.strip()
        duplicated_data = ToDoModel.objects.filter(
            autor=request.user,
            tarefa=no_space
        )
        occurrence = len(duplicated_data)
        
        if occurrence >= 1:
            messages.warning(request, 'Esta tarefa já está cadastrada!')
            del(request.session['register_form_data'])
            return redirect(reverse('todo:list'))
        else:
            data.autor=request.user
            data.concluida=False
            data.save()
        
            messages.success(request, 'Tarefa adicionada!')
            del(request.session['register_form_data'])
        
            return redirect(reverse('todo:list'))
    else:
        messages.error(request, form.errors['tarefa'][0])
      
        del(request.session['register_form_data'])
        return redirect(reverse('todo:list'))
        

@login_required(login_url='authentication:logon', redirect_field_name='next')
def update_task(request, id):
    tarefa = get_object_or_404(ToDoModel, pk=id)
    
    if tarefa.concluida:
        tarefa.concluida=False
        tarefa.save()
        return redirect('todo:list')
    else:
        tarefa.concluida=True
        tarefa.save()
        return redirect('todo:list')


@login_required(login_url='authentication:logon', redirect_field_name='next')
def delete_task(request, id):
    tarefa = get_object_or_404(ToDoModel, pk=id)
    tarefa.delete()
    return redirect('todo:list')

todo/templates/todo/todo_list.html
{% extends 'base.html' %}

{% block title %}Tarefas | Lista{% endblock %}

{% block main %}
<div class="header-tasklist">
    <div class="title-todo">Tarefas</div>

    <div class="form-adding">
        <form class="form-adding-list" action="{% url 'todo:create' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
            {{field}}
            {% endfor %}
        <button type="submit">Adicionar</button>
        </form>
    </div>

    <div class="logged-user">
        <p>Usuário</p>
        {% if request.user.is_authenticated %}
        <p>{{request.user.first_name}}</p>
        {% endif %}
    </div>
    
    <div class="logout-user" >
        <!--Evitar link malicioso -->
        <form action="{% url 'authentication:logout'%}" method="post">
        {% csrf_token %}
        <input type="hidden" name="username" value="{{request.user.username}}">
        <button type="submit" class="logout-plaintext-buttom"><span>Sair</span><i class="fa-solid fa-person-walking-arrow-right"></i></button>
        </form>
    </div>

    <div class="user-settings" >
        <a href="{% url 'authentication:settings'%}">
            <i class="fa-solid fa-user-gear"></i>
            <p>Configurações</p>
        </a>
    </div>

</div>

<div class="list-todo">
    {% include 'parts/messages.html' %}
    
    {% if not lista %}
    <div class="not-todo">    
        <div class="not-todo-message">
        <p><i class="fa-solid fa-circle-exclamation"></i></p>
        <p>Você ainda não possui tarefas cadastradas!</p>
        </div>

        <div class="grid-navigation">
            <a class="navigation-button" href="{% url 'home:index' %}"><i class="fa-solid fa-circle-arrow-left"></i></a> 
        </div>
    </div>

    {% else %}

    <div class="container mt-3">
        <!-- Card's task -->
        <div class="list-grid">
            {% for item in lista %}
                <div class="card">
                    {% if item.concluida %}
                    <div class="card-header card-header-red">{{item.data_de_criacao}}</div>
                    {% else %}
                    <div class="card-header card-header-green">{{item.data_de_criacao}}</div>
                    {% endif %}
                    <div class="card-body">
                        {% if item.concluida %}
                        <div class="card-text card-text-body-red">{{item.tarefa}}</div>
                        {% else %}
                        <div class="card-text card-text-body-green">{{item.tarefa}}</div>
                        {% endif %}
                        <div class="card-actions">
                            {% if item.concluida %}
                            <a class="buttom card-actions-red" href="{% url 'todo:update' item.id %}">Reabrir tarefa</a>
                            {% else %}
                            <a class="buttom card-actions-green" href="{% url 'todo:update' item.id %}">Concluir</a>
                            {% endif %}
                            
                            {% if not item.concluida %}
                            <!-- não excluir se tarefa ainda está em aberto -->
                            {% else %}
                            <a class="buttom card-actions-red" href="{% url 'todo:delete' item.id %}" onclick="return confirm('Quer mesmo excluir esta tarefa?');">
                                Excluir
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-navigation">
            <a class="navigation-button" href="{% url 'home:index' %}"><i class="fa-solid fa-circle-arrow-left"></i></a> 
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}